/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getJsResponseTimeout(): number

export declare function getMaxBodyBytes(): number

export declare function registerJsCallback(callback: ((err: Error | null, arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Buffer, arg6: string, arg7: string) => string)): void

export declare function respond(reqId: string, payload: string): void

/** Exposed: parse a Buffer asynchronously (returns Promise -> JS object) */
export declare function serdeParseAsync(input: Buffer): Promise<unknown>

/**
 * Exposed: stringify asynchronously. Accepts a JS string (which we will parse then re-serialize).
 * Returns a Promise resolving to a JS string.
 */
export declare function serdeStringifyAsync(input: string): Promise<string>

export declare function setJsResponseTimeout(secs: number): void

export declare function setMaxBodyBytes(bytes: number): void

export declare function startServer(host?: string | undefined | null, port?: number | undefined | null): Promise<void>
