/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function clearRustHotpaths(): void

export declare function getJsResponseTimeout(): number

export declare function getMaxBodyBytes(): number

export declare function listRustHotpaths(): Array<string>

export declare function registerJsCallback(callback: ((err: Error | null, arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Buffer, arg6: string, arg7: string) => string)): void

export declare function registerRustHotpath(method: string, path: string, status?: number | undefined | null, headersJson?: string | undefined | null, body?: Buffer | undefined | null, includeRequest?: boolean | undefined | null): void

export declare function removeRustHotpath(method: string, path: string): boolean

export declare function respond(reqId: string, status: number, headersJson: string | undefined | null, cookiesJson: string | undefined | null, body: Buffer): void

export declare function setJsResponseTimeout(secs: number): void

export declare function setMaxBodyBytes(bytes: number): void

export declare function startServer(host?: string | undefined | null, port?: number | undefined | null, forceNewRuntime?: boolean | undefined | null): void
