/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function readFile(path: string): string

export declare function registerJsCallback(callback: ((err: Error | null, arg0: string, arg1: string, arg2: string, arg3: string) => string)): void

export declare function startServer(host?: string | undefined | null, port?: number | undefined | null): Promise<void>
